# Generated by Django 5.0.1 on 2024-02-03 05:30

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderForm',
            fields=[
                ('deliveryorderid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vendorname', models.CharField(default='vendorname', max_length=30)),
                ('vendoraddress', models.CharField(default='Cyberjaya', max_length=200)),
                ('recipientname', models.CharField(default='recipientName', max_length=30)),
                ('recipientphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('recipientaddress', models.CharField(default='recipientaddress', max_length=200)),
                ('deliveryorderdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliveryorderstatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1)),
                ('courierstatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1)),
                ('invoicestatus', models.IntegerField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1)),
                ('invoicecreated', models.BooleanField(default=False)),
                ('itemid', models.IntegerField(default=0)),
                ('itemprice', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('itemdescription', models.CharField(default='empty', max_length=30)),
                ('itemquantity', models.IntegerField(default=0)),
                ('invoicetotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
    ]
