# Generated by Django 4.1.5 on 2023-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
