# Generated by Django 4.1.5 on 2023-01-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0002_item_itemprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryOrder',
            new_name='DeliveryOrderForm',
        ),
    ]
