# Generated by Django 4.1.5 on 2023-01-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0003_rename_deliveryorder_deliveryorderform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderFormItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuantity', models.IntegerField(default=0)),
                ('deliveryOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryorder.deliveryorderform')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveryorder.item')),
            ],
        ),
    ]
