# Generated by Django 4.1.5 on 2023-01-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0004_deliveryorderformitemlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryOrderFormItemList',
            new_name='TableList',
        ),
    ]
