# Generated by Django 4.1.5 on 2023-01-14 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0005_rename_deliveryorderformitemlist_tablelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='deliveryOrderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 40, 52, 530977, tzinfo=datetime.timezone.utc)),
        ),
    ]
