# Generated by Django 4.1.5 on 2023-01-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0006_deliveryorderform_deliveryorderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderform',
            name='deliveryOrderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 15, 35, 16, 130542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deliveryorderform',
            name='deliveryOrderStatus',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Disapproved'), (2, 'Approved')], default=0),
        ),
    ]
