# Generated by Django 4.1.5 on 2023-01-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0008_alter_deliveryorderform_deliveryorderdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='itemID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='deliveryorder.item'),
        ),
        migrations.AddField(
            model_name='deliveryorderform',
            name='itemQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TableList',
        ),
    ]
