# Generated by Django 4.1.5 on 2023-01-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0009_deliveryorderform_itemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderform',
            name='itemID',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='deliveryorder.item'),
        ),
    ]
