# Generated by Django 4.1.5 on 2023-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0011_alter_deliveryorderform_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='itemDescription',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryorderform',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='deliveryorderform',
            name='itemID',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
