# Generated by Django 4.1.5 on 2023-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0012_deliveryorderform_itemdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderform',
            name='recipientAddress',
            field=models.CharField(default='recipientaddress', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryorderform',
            name='recipientName',
            field=models.CharField(default='recipientName', max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryorderform',
            name='vendorAddress',
            field=models.CharField(default='Cyberjaya', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryorderform',
            name='vendorName',
            field=models.CharField(default='vendorname', max_length=30),
        ),
    ]
