# Generated by Django 4.1.5 on 2023-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0013_alter_deliveryorderform_recipientaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='courierStatus',
            field=models.BooleanField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1),
        ),
        migrations.AddField(
            model_name='deliveryorderform',
            name='invoiceTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
