# Generated by Django 4.1.5 on 2023-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0014_deliveryorderform_courierstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderform',
            name='courierStatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1),
        ),
    ]
