# Generated by Django 4.1.5 on 2023-01-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0016_deliveryorderform_invoicestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorderform',
            name='invoiceStatus',
        ),
    ]
