# Generated by Django 4.1.5 on 2023-01-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0017_remove_deliveryorderform_invoicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='invoiceStatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Disapproved'), (3, 'Approved')], default=1),
        ),
    ]
