# Generated by Django 4.1.5 on 2023-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryorder', '0018_deliveryorderform_invoicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderform',
            name='invoiceCreated',
            field=models.BooleanField(default=False),
        ),
    ]
